name: Dev Build

on:
  pull_request:
    branches:
      - "[0-9]*.[0-9]*.[0-9]*"

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  # ----------------------------------------------------------------
  # Linux
  # ----------------------------------------------------------------
  build-linux-x64:
    name: Build Linux x64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install X11 dev
        run: sudo apt-get update && sudo apt-get install -y libx11-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: "==3.3.*"
          version: "6.8.3"
          host: "linux"
          target: "desktop"
          arch: "linux_gcc_64"
          cache: true

      - name: Build
        run: make build

      - name: Show dist/ structure
        run: tree -a dist/

  # ----------------------------------------------------------------
  # Windows
  # ----------------------------------------------------------------
  build-win-x64:
    name: Build Windows x64
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.3"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          cache: true

      - name: Build
        run: make build

      - name: Show dist/ structure
        run: tree /f dist\

  # ----------------------------------------------------------------
  # macOS
  # ----------------------------------------------------------------
  build-macos-arm64:
    name: Build macOS ARM64
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.3"
          host: "mac"
          target: "desktop"
          arch: "clang_64"
          cache: true

      - name: Build
        run: make build

      - name: Install tree
        run: brew install tree

      - name: Show dist/ structure
        run: tree -a dist/
